### ISSUE TITLE
Implement User Account System

### ISSUE THREAD

**Issue by rothlisbergerc** [rothlisbergerc/GroomingSalonWebsite#101]
Users should be able to create their own account that stores their personal information and appointment information for convenient retrieval.  Users should be able to sign in and out via a button found in the upper right corner on the nav bar. 

There should be an administrative log in that shows the database test pages. These pages will be hidden to regular users. 

This issue will be updated and refined as the project progresses.

**Comment by RyderDProgrammer** [comment]
Find a way to have user passwords incrypted, also needs to be added to this.
