### ISSUE TITLE
Beautify the account creation and login pages

### ISSUE THREAD

**Issue by RyderDProgrammer** [rothlisbergerc/GroomingSalonWebsite#111]
I created the pages so that way I would be able to do back end code on them as testing but they are very ugly and need to be reworked into their best.

- [x] make error text more readable
- [x] Change header on registration page from "Login to your Account!" to "Create a New Account"
- [x] rearrange form layout to be more consistent to the home page

**Comment by rothlisbergerc** [comment]
need to make the error text more readable.

**Comment by rothlisbergerc** [comment]
Wasn't able to change error text color/background without breaking other stuff. Altered all the error text to be bold as a compramise.
